spring:
 profiles: "dev"
 datasource:
  driverClassName: 'oracle.jdbc.driver.OracleDriver'
  username: onair
  password: nbcci
  url: jdbc:oracle:thin:@//aoadbss00002c0.tfayd.com:15192/S123
 jpa:
  show-sql: true
  database-platform: 'org.hibernate.dialect.Oracle10gDialect'
  hibernate:
   ddl-auto: none   
logging:
  level:
    webapp: DEBUG
  file: c:/application.log
---
spring:
 profiles:
  active: "dev"